from __future__ import annotations

from typing import Final

PermissionItem = tuple[str, str]

PERMISSION_CATALOG: Final[tuple[PermissionItem, ...]] = (
    ("system.read", "Read system status."),
    ("system.manage", "Manage service-level operations."),
    ("auth.me", "Read own authenticated profile."),
    ("auth.logout", "Create logout requests."),
    ("users.read", "Read user records."),
    ("users.manage_discord_roles_cache", "Manage cached user-role memberships."),
    ("discord_roles.read", "Read synchronized Discord roles."),
    ("discord_roles.sync", "Synchronize roles from Discord guild."),
    ("discord_role_permissions.read", "Read role to permission matrix."),
    ("discord_role_permissions.write", "Update role to permission matrix."),
    ("permissions.read", "Read permission definitions."),
    ("permissions.manage", "Manage permissions and mapping."),
    ("config_registry.read", "Read configuration registry."),
    ("config_registry.write", "Update configuration registry."),
    ("config_registry.rollback", "Rollback configuration keys."),
    ("config_registry.preview", "Preview configuration updates."),
    ("config_change.approve", "Approve critical configuration changes."),
    ("applications.create_guest", "Create applications as guest."),
    ("applications.create_member", "Create applications as member."),
    ("applications.eligibility.read", "Read application eligibility."),
    ("applications.read_public", "Read public application data."),
    ("applications.read_private", "Read private application details."),
    ("applications.review", "Review applications."),
    ("applications.assign_reviewer", "Assign application reviewers."),
    ("applications.decision.accept", "Accept applications."),
    ("applications.decision.decline", "Decline applications."),
    ("applications.reapply_policy.write", "Configure re-apply policy."),
    ("applications.policies.read", "Read application policies."),
    ("applications.policies.write", "Write application policies."),
    ("applications.comment", "Comment on applications."),
    ("applications.export", "Export application data."),
    ("voting.read", "Read voting state."),
    ("voting.cast", "Cast votes."),
    ("voting.list_voters", "Read voter identities."),
    ("voting.close", "Close voting context."),
    ("voting.reopen", "Re-open voting context."),
    ("voting.reset", "Reset voting state."),
    ("orders.submit", "Submit orders."),
    ("orders.read", "Read orders."),
    ("orders.review", "Review orders."),
    ("orders.decision.accept", "Accept orders."),
    ("orders.decision.deny", "Deny orders."),
    ("orders.export", "Export orders."),
    ("verification_requests.create", "Create account verification requests."),
    ("verification_requests.read_own", "Read own account verification requests."),
    ("verification_requests.read", "Read account verification requests."),
    ("verification_requests.review", "Review account verification requests."),
    ("posts.read_public", "Read public landing posts."),
    ("posts.read", "Read landing posts in dashboard context."),
    ("posts.write", "Create and edit landing posts."),
    ("posts.publish", "Publish or unpublish landing posts."),
    ("user_account_link.read", "Read user account links."),
    ("user_account_link.write", "Manage user account links."),
    ("playerbase.read", "Read playerbase records."),
    ("playerbase.write", "Manage playerbase records."),
    ("roster.read", "Read roster records."),
    ("roster.write", "Manage roster records."),
    ("ranks.read", "Read rank definitions."),
    ("ranks.write", "Manage rank definitions."),
    ("blacklist.read", "Read blacklist entries."),
    ("blacklist.add", "Add blacklist entries."),
    ("blacklist.update", "Update blacklist entries."),
    ("blacklist.level.write", "Update blacklist level rules."),
    ("blacklist.remove", "Remove blacklist entries."),
    ("blacklist.restore", "Restore removed blacklist entries."),
    ("blacklist_removal_requests.create", "Create blacklist removal requests."),
    ("blacklist_removal_requests.read", "Read blacklist removal requests."),
    ("blacklist_removal_requests.review", "Review blacklist removal requests."),
    ("punishments.read", "Read punishments."),
    ("punishments.write", "Manage punishments."),
    ("activities.read", "Read activities."),
    ("activities.create", "Create activities."),
    ("activities.approve", "Approve activities."),
    ("activities.reject", "Reject activities."),
    ("activities.manage_participants", "Manage activity participants."),
    ("activities.publish_forum", "Publish activities to forums."),
    ("vacations.read", "Read vacation requests."),
    ("vacations.submit", "Submit vacation requests."),
    ("vacations.approve", "Approve vacation requests."),
    ("vacations.deny", "Deny vacation requests."),
    ("vacations.cancel", "Cancel vacation requests."),
    ("vacations.configure_thresholds", "Configure vacation thresholds."),
    ("notifications.read", "Read personal notifications."),
    ("notifications.broadcast", "Broadcast high-staff notifications."),
    ("notifications.send_targeted", "Send targeted notifications."),
    ("notifications.delete_own", "Delete own notification deliveries."),
    ("policies.configure_role_thresholds", "Configure role thresholds."),
    ("bot.read_status", "Read bot operational state."),
    ("bot.configure_channels", "Configure bot channel routing."),
    ("bot.toggle_features", "Toggle bot feature flags."),
    ("bot.trigger.forum_sync", "Trigger forum synchronization."),
    ("bot.trigger.cop_scores_refresh", "Trigger cop score refresh."),
    ("bot.replay_dead_letter", "Replay failed bot IPC commands from dead-letter queue."),
    ("bot.manage.voting", "Manage backend-owned voting operations."),
    ("bot.manage.recruitment", "Manage recruitment operations."),
    ("config.read", "Read general configuration."),
    ("config.write", "Write general configuration."),
    ("audit.read", "Read audit timeline and traces."),
    ("owner.override", "Bypass authorization checks as owner."),
)

INITIAL_MEMBER_PERMISSION_BUNDLE: Final[tuple[str, ...]] = (
    "applications.create_member",
    "applications.read_public",
    "verification_requests.create",
    "verification_requests.read_own",
    "voting.cast",
    "orders.submit",
    "activities.create",
    "vacations.submit",
    "notifications.read",
)

CRITICAL_CONFIG_KEYS: Final[set[str]] = {
    "permissions.role_matrix",
    "bot.service_toggles",
    "bot.channel_routing",
    "voting.auto_close_days",
    "applications.default_denial_cooldown_days",
    "vacations.max_duration_days",
}
